In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/Enjoysport - Sheet1.csv")

In [ ]:
df

   Example    Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0        1  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1        2  Sunny    Warm     High  Strong  Warm     Same        Yes
2        3  Rainy    Cold     High  Strong  Warm   Change         No
3        4  Sunny    Warm     High  Strong  Cool   Change        Yes

In [ ]:
df.drop("Example",axis=True)

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes

In [ ]:
test = df['EnjoySport']
test

0    Yes
1    Yes
2     No
3    Yes
Name: EnjoySport, dtype: object

In [ ]:
train = df[['Sky','AirTemp','Humidity','Wind','Water','Forecast']]
train

     Sky AirTemp Humidity    Wind Water Forecast
0  Sunny    Warm   Normal  Strong  Warm     Same
1  Sunny    Warm     High  Strong  Warm     Same
2  Rainy    Cold     High  Strong  Warm   Change
3  Sunny    Warm     High  Strong  Cool   Change

In [ ]:
target = np.array(test)
train = np.array(train)

In [ ]:
print("Instances are")
print(train)
print("Target are")
print(target)

Instances are
[['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
 ['Sunny' 'Warm' 'High' 'Strong' 'Warm' 'Same']
 ['Rainy' 'Cold' 'High' 'Strong' 'Warm' 'Change']
 ['Sunny' 'Warm' 'High' 'Strong' 'Cool' 'Change']]
Target are
['Yes' 'Yes' 'No' 'Yes']

In [ ]:
def learn(concepts, target): 
    specific_h = ["null"]*len(concepts[0])
    print("\nInitialization of specific_h and genearal_h")
    print("\nSpecific Boundary: ", specific_h)
    specific_h = concepts[0].copy()
    general_h = [["?" for i in range(len(specific_h))] for i in range(len(specific_h))]
    print("\nGeneric Boundary: ",general_h)  

    for i, h in enumerate(concepts):
        print("\nInstance", i+1 , "is ", h)
        if target[i] == "Yes":
            print("Instance is Positive ")
            for x in range(len(specific_h)): 
                if h[x]!= specific_h[x]:                    
                    specific_h[x] ='?'                     
                    general_h[x][x] ='?'
                   
        if target[i] == "No":            
            print("Instance is Negative ")
            for x in range(len(specific_h)): 
                if h[x]!= specific_h[x]:                    
                    general_h[x][x] = specific_h[x]                
                else:                    
                    general_h[x][x] = '?'        
        
        print("Specific Bundary after ", i+1, "Instance is ", specific_h)         
        print("Generic Boundary after ", i+1, "Instance is ", general_h)
        print("\n")

    indices = [i for i, val in enumerate(general_h) if val == ['?']*len(concepts[0])]    
    for i in indices:   
        general_h.remove(['?', '?', '?', '?', '?', '?']) 
    return specific_h, general_h

In [ ]:
s_final, g_final = learn(train, target)

print("Final Specific_h: ", s_final, sep="\n")
print("Final General_h: ", g_final, sep="\n")

Initialization of specific_h and genearal_h

Specific Boundary:  ['null', 'null', 'null', 'null', 'null', 'null']

Generic Boundary:  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Instance 1 is  ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Instance is Positive
Specific Bundary after  1 Instance is  ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Generic Boundary after  1 Instance is  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]



Instance 2 is  ['Sunny' 'Warm' 'High' 'Strong' 'Warm' 'Same']
Instance is Positive
Specific Bundary after  2 Instance is  ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
Generic Boundary after  2 Instance is  [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]



Instance 3 is  ['Rainy' 'Cold' 'High' 'Strong' 'Warm' 'Change']
Instance is Negative
Specific Bundary after  3 Instance is  ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
Generic Boundary after  3 Instance is  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]



Instance 4 is  ['Sunny' 'Warm' 'High' 'Strong' 'Cool' 'Change']
Instance is Positive
Specific Bundary after  4 Instance is  ['Sunny' 'Warm' '?' 'Strong' '?' '?']
Generic Boundary after  4 Instance is  [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]


Final Specific_h:
['Sunny' 'Warm' '?' 'Strong' '?' '?']
Final General_h:
[['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]

In [ ]:
import gspread as gs

In [4]:
df = pd.read_csv("/content/drive/MyDrive/ML-Datasets/Buy.csv")

In [5]:
df

   Example citations    size inLibrary       price editions  buy
0        1      some   small        no  affordable     many   no
1        2      many     big        no   expensive      one  yes
2        3      some     big    always   expensive      few   no
3        4      many  medium        no   expensive     many  yes
4        5      many   small        no  affordable     many  yes

In [6]:
df = df.drop("Example",axis = True)

In [7]:
test = df['buy']
test

0     no
1    yes
2     no
3    yes
4    yes
Name: buy, dtype: object

In [8]:
train = df[['citations','size','inLibrary','price','editions']]
train

  citations    size inLibrary       price editions
0      some   small        no  affordable     many
1      many     big        no   expensive      one
2      some     big    always   expensive      few
3      many  medium        no   expensive     many
4      many   small        no  affordable     many

In [19]:
target = np.array(test)
train = np.array(train)

In [21]:
print("Instances are")
print(train)
print("Target are")
print(target)

Instances are
[['some' 'small' 'no' 'affordable' 'many']
 ['many' 'big' 'no' 'expensive' 'one']
 ['some' 'big' 'always' 'expensive' 'few']
 ['many' 'medium' 'no' 'expensive' 'many']
 ['many' 'small' 'no' 'affordable' 'many']]
Target are
['no' 'yes' 'no' 'yes' 'yes']

In [22]:
def learn(concepts, target): 
    specific_h = ["null"]*len(concepts[0])
    print("\nInitialization of specific_h and genearal_h")
    print("\nSpecific Boundary: ", specific_h)
    specific_h = concepts[1].copy()
    general_h = [["?" for i in range(len(specific_h))] for i in range(len(specific_h))]
    print("\nGeneric Boundary: ",general_h)  

    for i, h in enumerate(concepts):
        print("\nInstance", i+1 , "is ", h)
        if target[i] == "yes":
            print("Instance is Positive ")
            for x in range(len(specific_h)): 
                if h[x]!= specific_h[x]:                    
                    specific_h[x] ='?'                     
                    general_h[x][x] ='?'
                   
        if target[i] == "no":            
            print("Instance is Negative ")
            for x in range(len(specific_h)): 
                if h[x]!= specific_h[x]:                    
                    general_h[x][x] = specific_h[x]                
                else:                    
                    general_h[x][x] = '?'        
        
        print("Specific Bundary after ", i+1, "Instance is ", specific_h)         
        print("Generic Boundary after ", i+1, "Instance is ", general_h)
        print("\n")

    indices = [i for i, val in enumerate(general_h) if val == ['?']*len(concepts[0])]    
    for i in indices:   
        general_h.remove(['?', '?', '?', '?', '?']) 
    return specific_h, general_h

In [23]:
s_final, g_final = learn(train, target)

print("Final Specific_h: ", s_final, sep="\n")
print("Final General_h: ", g_final, sep="\n")

Initialization of specific_h and genearal_h

Specific Boundary:  ['null', 'null', 'null', 'null', 'null']

Generic Boundary:  [['?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?']]

Instance 1 is  ['some' 'small' 'no' 'affordable' 'many']
Instance is Negative
Specific Bundary after  1 Instance is  ['many' 'big' 'no' 'expensive' 'one']
Generic Boundary after  1 Instance is  [['many', '?', '?', '?', '?'], ['?', 'big', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', 'expensive', '?'], ['?', '?', '?', '?', 'one']]



Instance 2 is  ['many' 'big' 'no' 'expensive' 'one']
Instance is Positive
Specific Bundary after  2 Instance is  ['many' 'big' 'no' 'expensive' 'one']
Generic Boundary after  2 Instance is  [['many', '?', '?', '?', '?'], ['?', 'big', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', 'expensive', '?'], ['?', '?', '?', '?', 'one']]



Instance 3 is  ['some' 'big' 'always' 'expensive' 'few']
Instance is Negative
Specific Bundary after  3 Instance is  ['many' 'big' 'no' 'expensive' 'one']
Generic Boundary after  3 Instance is  [['many', '?', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', 'no', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', '?', 'one']]



Instance 4 is  ['many' 'medium' 'no' 'expensive' 'many']
Instance is Positive
Specific Bundary after  4 Instance is  ['many' '?' 'no' 'expensive' '?']
Generic Boundary after  4 Instance is  [['many', '?', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', 'no', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?']]



Instance 5 is  ['many' 'small' 'no' 'affordable' 'many']
Instance is Positive
Specific Bundary after  5 Instance is  ['many' '?' 'no' '?' '?']
Generic Boundary after  5 Instance is  [['many', '?', '?', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', 'no', '?', '?'], ['?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?']]


Final Specific_h:
['many' '?' 'no' '?' '?']
Final General_h:
[['many', '?', '?', '?', '?'], ['?', '?', 'no', '?', '?']]